export const plotsData = [
  { id: 'S-01', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-02', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-03', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-04', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-05', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-06', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-07', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-08', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-09', type: 'Shop Plot', sqyd: 30.55, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-10', type: 'Shop Plot', sqyd: 30.33, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-11', type: 'Shop Plot', sqyd: 30.33, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-12', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-13', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-14', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-15', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-16', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-17', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-18', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-19', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-20', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-21', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-22', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-23', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-24', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-25', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-26', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-27', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-28', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-29', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-30', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-31', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-32', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-33', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-34', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-35', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-36', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-37', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-38', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-39', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-40', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-41', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-42', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-43', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-44', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-45', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-46', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-47', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-48', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-49', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-50', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-51', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-52', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-53', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-54', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-55', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-56', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-57', type: 'Shop Plot', sqyd: 27.78, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'S-58', type: 'Shop Plot', sqyd: 35.69, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-01', type: 'Commercial Plot', sqyd: 26.51, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-02', type: 'Commercial Plot', sqyd: 65.27, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-03', type: 'Commercial Plot', sqyd: 98.88, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-04', type: 'Commercial Plot', sqyd: 128.14, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-05', type: 'Commercial Plot', sqyd: 190.48, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-06', type: 'Commercial Plot', sqyd: 200.0, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-07', type: 'Commercial Plot', sqyd: 222.77, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-08', type: 'Commercial Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-09', type: 'Commercial Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-10', type: 'Commercial Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-11', type: 'Commercial Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-12', type: 'Commercial Plot', sqyd: 222.22, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-13', type: 'Commercial Plot', sqyd: 222.22, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-14', type: 'Commercial Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-15', type: 'Commercial Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-16', type: 'Commercial Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-17', type: 'Commercial Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-18', type: 'Commercial Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-19', type: 'Commercial Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-20', type: 'Commercial Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-21', type: 'Commercial Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'C-22', type: 'Commercial Plot', sqyd: 199.3, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 01', type: 'Residential Plot', sqyd: 147.47, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 02', type: 'Residential Plot', sqyd: 109.08, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 03', type: 'Residential Plot', sqyd: 213.75, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 04', type: 'Residential Plot', sqyd: 271.25, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 05', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 06', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 07', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 08', type: 'Residential Plot', sqyd: 81.25, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 09', type: 'Residential Plot', sqyd: 177.3, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 10', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 11', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 12', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 13', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 14', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 15', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 16', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 17', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 18', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 19', type: 'Residential Plot', sqyd: 142.55, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 20', type: 'Residential Plot', sqyd: 195.7, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 21', type: 'Residential Plot', sqyd: 138.88, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 22', type: 'Residential Plot', sqyd: 206.55, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 23', type: 'Residential Plot', sqyd: 178.94, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 24', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 25', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 26', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 27', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 28', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 29', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 30', type: 'Residential Plot', sqyd: 138.88, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 31', type: 'Residential Plot', sqyd: 138.88, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 32', type: 'Residential Plot', sqyd: 138.88, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 33', type: 'Residential Plot', sqyd: 138.88, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 34', type: 'Residential Plot', sqyd: 138.88, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 35', type: 'Residential Plot', sqyd: 138.88, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 36', type: 'Residential Plot', sqyd: 171.52, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 37', type: 'Residential Plot', sqyd: 179.86, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 38', type: 'Residential Plot', sqyd: 138.88, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 39', type: 'Residential Plot', sqyd: 138.88, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 40', type: 'Residential Plot', sqyd: 138.88, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 41', type: 'Residential Plot', sqyd: 138.88, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 42', type: 'Residential Plot', sqyd: 138.88, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 43', type: 'Residential Plot', sqyd: 138.88, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 44', type: 'Residential Plot', sqyd: 138.88, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 45', type: 'Residential Plot', sqyd: 138.88, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 46', type: 'Residential Plot', sqyd: 82.86, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 47', type: 'Residential Plot', sqyd: 166.66, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 48', type: 'Residential Plot', sqyd: 179.16, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 49', type: 'Residential Plot', sqyd: 182.19, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 50', type: 'Residential Plot', sqyd: 227.93, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 51', type: 'Residential Plot', sqyd: 307.83, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
  { id: 'Plot 52', type: 'Residential Plot', sqyd: 1573.2, rate: 0, status: 'Available', buyer: '', date: '', advance: 0 },
];
